### PR TITLE
Refactor Vagrantfile

### PR DESCRIPTION
**Pull request by srisankethu**
Closes https://github.com/dfarrell07/vagrant-opendaylight/issues/32

Signed-off-by: srisankethu <sanketh.uppalapati@research.iiit.ac.in>

### CODE REVIEW

**Comment by dfarrell07** [comment]
It looks like you've combined definitions for things like li_sr{1..n}, but not across major ODL versions for an otherwise-same deployment (same OS, deployment method). Imho we should use numerical versions and iterate over all the ones we care about, like {34, 41, 42, 43, 44, 50, 51}.

**Comment by dfarrell07** [comment]
I also wonder if there's any worthwhile deduplication we could do with nested loops (like for OS, install type as well as ODL version).

**Comment by srisankethu** [comment]
@dfarrell07 Yes! there is de-duplication that could be done. But I was concerned if the changes would help adding new boxes(which **might** need certain exceptions) simpler. Initially, I have combined the debian and ubuntu boxes, most of the centOS boxes have same logic, ansible and  puppet boxes across different OSs are same.
    Should have saved my patch :( Need to do that again!

**Comment by srisankethu** [comment]
@dfarrell07 I improved the patch. Take a look at it whenever you are free :+1:

**Comment by dfarrell07** [comment]
Cool, looks like a major improvement to me. Thanks! :+1:

**Pull request merged**
